#!/bin/bash
#SBATCH --output=Acinetobacter_baumannii_batch_file_output_1
#SBATCH --cpus-per-task=1
#SBATCH --mem=16G


python3 ../../Generate_Identity_Score.py Acinetobacter_baumannii Acinetobacter_baumannii_RNA_chain_list_1 1 100 
