#!/bin/bash
#SBATCH --output=Enterococcus_faecalis_batch_file_output_1
#SBATCH --cpus-per-task=1
#SBATCH --mem=16G


python3 ../../Generate_Identity_Score.py Enterococcus_faecalis Enterococcus_faecalis_RNA_chain_list_1 1 100 
