#!/bin/bash
#SBATCH --output=Escherichia_coli_batch_file_output_1
#SBATCH --cpus-per-task=1
#SBATCH --mem=16G


python3 ../../Generate_Identity_Score.py Escherichia_coli Escherichia_coli_RNA_chain_list_1 1 100 
