#!/bin/bash
#SBATCH --output=Haloarcula_marismortui_batch_file_output_1
#SBATCH --cpus-per-task=1
#SBATCH --mem=16G


python3 ../../Generate_Identity_Score.py Haloarcula_marismortui Haloarcula_marismortui_RNA_chain_list_1 1 100 
