#!/bin/bash
#SBATCH --output=Align_Mus_musculus_batch_file_output_1_list_1
#SBATCH --cpus-per-task=1
#SBATCH --mem=16G


python3 ../../Generate_RMSD_Align_from_Connected_Graph_Parallel_Batch_file.py Mus_musculus Mus_musculus_cluster_1 Mus_musculus_cluster_1_list_1 50 1 
