#!/bin/bash
#SBATCH --output=Preprocess_Bacillus_subtilis_batch_file_output_4_list_1
#SBATCH --cpus-per-task=1
#SBATCH --mem=16G


python3 ../../Generate_RMSD_Preprocess_from_Connected_Graph_Parallel_Batch_file.py Bacillus_subtilis Bacillus_subtilis_cluster_4 Bacillus_subtilis_cluster_4_list_1 50 1 
