#!/bin/bash
#SBATCH --output=Preprocess_Acinetobacter_baumannii_batch_file_output_4_list_1
#SBATCH --cpus-per-task=1
#SBATCH --mem=16G


python3 ../../Generate_RMSD_Preprocess_from_Connected_Graph_Parallel_Batch_file.py Acinetobacter_baumannii Acinetobacter_baumannii_cluster_4 Acinetobacter_baumannii_cluster_4_list_1 50 1 
