#!/bin/bash
#SBATCH --output=Preprocess_Haloarcula_marismortui_batch_file_output_1_list_1
#SBATCH --cpus-per-task=1
#SBATCH --mem=16G


python3 ../../Generate_RMSD_Preprocess_from_Connected_Graph_Parallel_Batch_file.py Haloarcula_marismortui Haloarcula_marismortui_cluster_1 Haloarcula_marismortui_cluster_1_list_1 50 1 
